apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - common/config.yaml
  - fpm/deployment.yaml
  - fpm/service.yaml
  - queue-workers/deployment-default.yaml
  - webserver/deployment.yaml
  - webserver/service.yaml
  - webserver/ingress.yaml
  # - ingress-controller/controller.yaml
