runtime: php81
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1

runtime_config:
  document_root: public

# for detecting static files in the public folder
handlers:
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
env_variables:
  APP_KEY: $APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  DB_CONNECTION: $DB_CONNECTION
  DB_HOST: $DB_HOST
  DB_PORT: $DB_PORT
  DB_DATABASE: $DB_DATABASE
  DB_USERNAME: $DB_USERNAME
  DB_PASSWORD: $DB_PASSWORD
  MYSQL_ATTR_SSL_CA: $MYSQL_ATTR_SSL_CA
  APP_NAME: "SureBack"
  APP_ENV: production
  APP_DEBUG: "true"
  APP_URL: $APP_URL
  ASSET_URL: $ASSET_URL
  SESSION_DRIVER: $SESSION_DRIVER
  QUEUE_CONNECTION: $QUEUE_CONNECTION
  MAIL_MAILER: $MAIL_MAILER
  MAIL_HOST: $MAIL_HOST
  MAIL_PORT: $MAIL_PORT
  MAIL_USERNAME: $MAIL_USERNAME
  MAIL_PASSWORD: $MAIL_PASSWORD
  MAIL_ENCRYPTION: $MAIL_ENCRYPTION
  MAIL_FROM_ADDRESS: $MAIL_FROM_ADDRESS
  MAIL_FROM_NAME: $MAIL_FROM_NAME
  PUSHER_APP_ID: $PUSHER_APP_ID
  PUSHER_APP_KEY: $PUSHER_APP_KEY
  PUSHER_APP_SECRET: $PUSHER_APP_SECRET
  PUSHER_APP_CLUSTER: $PUSHER_APP_CLUSTER
  # the tmp folder is used for caching on GCP as opposed to the default storage folder
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
  RABBITMQ_HOST: $RABBITMQ_HOST
  RABBITMQ_PORT: $RABBITMQ_PORT
  RABBITMQ_USER: $RABBITMQ_USER
  RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
  RABBITMQ_VHOST: $RABBITMQ_VHOST

  FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
  FIREBASE_SERVER_KEY: $FIREBASE_SERVER_KEY
  FIREBASE_SENDER_ID: $FIREBASE_SENDER_ID

  CODE_CIPHERING: $CODE_CIPHERING
  CODE_DIGEST: $CODE_DIGEST
  CODE_ENCRYPTION_IV: $CODE_ENCRYPTION_IV
