version: "3"

networks:
    sureback:
        driver: bridge

services:
    # We need to run the FPM container for our application
    sureback.fpm: &fpm
        platform: linux/amd64
        build:
            context: .
            target: fpm_server
            args:
                APP_DIR: "${APP_DIR:-/var/www}"
        image: mfahmialkautsar/sureback-fpm_server
        restart: always
        # We can override any env values here.
        # By default the .env in the project root will be loaded as the environment for all containers
        env_file:
            - .env
        # Mount the codebase, so any code changes we make will be propagated to the running application
        volumes:
            # Here we mount in our codebase so any changes are immediately reflected into the container
            - ".:${APP_DIR:-/var/www}"
        networks:
            - sureback

    # Run the web server container for static content, and proxying to our FPM container
    sureback.web:
        platform: linux/amd64
        build:
            context: .
            target: web_server
            args:
                APP_DIR: "${APP_DIR:-/var/www}"
                SSL_CERT: "${SSL_CERT}"
                SSL_KEY: "${SSL_KEY}"
            #     TEMP_FILE_PATH: "${TEMP_FILE_PATH}"
        image: mfahmialkautsar/sureback-web_server
        restart: always
        # Expose our application port (80) through a port on our local machine (8080)
        ports:
            - "8080:80"
        environment:
            # We need to pass in the new FPM hst as the name of the fpm container on port 9000
            APP_ENV: "${APP_ENV:-production}"
            FPM_HOST: "sureback.fpm:9000"
            # TEMP_FILE_PATH: "${TEMP_FILE_PATH}"
        # Mount the public directory into the container so we can serve any static files directly when they change
        volumes:
            # Here we mount in our codebase so any changes are immediately reflected into the container
            - "./public:/opt/apps/sureback/public"
        networks:
            - sureback
        depends_on:
            - sureback.fpm

    # Queue Worker
    sureback.queue:
        <<: *fpm
        command: "php artisan queue:work --tries=3"
    # Run the Laravel Scheduler
    # sureback.cron:
    #     build:
    #         context: .
    #         target: cron
    #     image: mfahmialkautsar/sureback-cron
    #     # Here we mount in our codebase so any changes are immediately reflected into the container
    #     volumes:
    #         # Here we mount in our codebase so any changes are immediately reflected into the container
    #         - '.:/opt/apps/sureback'
    #     networks:
    #         - sureback
    # # Run the frontend, and file watcher in a container, so any changes are immediately compiled and servable
    # sureback.frontend:
    #     build:
    #         context: .
    #         target: frontend
    #     # Override the default CMD, so we can watch changes to frontend files, and re-transpile them.
    #     command: ["npm", "run", "watch"]
    #     image: mfahmialkautsar/sureback-frontend
    #     volumes:
    #         # Here we mount in our codebase so any changes are immediately reflected into the container
    #         - '.:/opt/apps/sureback'
    #         # Add node_modeules as singular volume.
    #         # This prevents our local node_modules from being propagated into the container,
    #         # So the node_modules can be compiled for each of the different architectures (Local, Image)
    #         - '/opt/app/node_modules/'
    #     networks:
    #         - sureback
