version: "3"

x-common-variables:
  &common-variables
  DB_CONNECTION: "${DB_CONNECTION:-mysql}"
  DB_HOST: "${DB_HOST:-mysql}"
  DB_PORT: "${DB_PORT:-3306}"
  DB_DATABASE: "${DB_DATABASE:-sail}"
  DB_USERNAME: "${DB_USERNAME:-sail}"
  DB_PASSWORD: "${DB_PASSWORD:-password}"
  REDIS_HOST: "${REDIS_HOST:-redis}"
  REDIS_PASSWORD: "${REDIS_PASSWORD:-null}"
  REDIS_PORT: "${REDIS_PORT:-6379}"
  MAIL_MAILER: "${MAIL_MAILER:-smtp}"
  MAIL_HOST: "${MAIL_HOST:-mailhog}"
  MAIL_PORT: "${MAIL_PORT:-1025}"
  MAIL_USERNAME: "${MAIL_USERNAME:-null}"
  MAIL_PASSWORD: "${MAIL_PASSWORD:-null}"
  MAIL_ENCRYPTION: "${MAIL_ENCRYPTION:-null}"
  MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
  MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
  PUSHER_APP_ID: "${PUSHER_APP_ID}"
  PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  PUSHER_APP_SECRET: "${PUSHER_APP_SECRET}"
  PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER:-mt1}"
  RABBITMQ_HOST: "${RABBITMQ_HOST}"
  RABBITMQ_PORT: "${RABBITMQ_PORT:-5672}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  RABBITMQ_VHOST: "${RABBITMQ_VHOST}"
  FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
  FIREBASE_SERVER_KEY: "${FIREBASE_SERVER_KEY}"
  FIREBASE_SENDER_ID: "${FIREBASE_SENDER_ID}"
  CODE_CIPHERING: "${CODE_CIPHERING}"
  CODE_DIGEST: "${CODE_DIGEST}"
  CODE_ENCRYPTION_IV: "${CODE_ENCRYPTION_IV}"

networks:
  main:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    restart: unless-stopped
    working_dir: /var/www
    environment:
      <<: *common-variables
    networks:
      - main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      # - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzz_custom.ini
  webserver:
    image: nginx:1.22.1-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      # - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./:/var/www
    networks:
      - main
    environment:
      <<: *common-variables
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue-worker
    tty: true
    restart: unless-stopped
    working_dir: /var/www
    environment:
      <<: *common-variables
    networks:
      - main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      # - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zzz_custom.ini
    command: php artisan queue:work --tries=3 --timeout=90
