apiVersion: apps/v1
kind: Deployment
metadata:
  name: sureback-fpm
  namespace: sureback-mfahmialkautsar
  labels:
    tier: backend
    layer: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      containers:
        - name: fpm
          image: ghcr.io/cro2one-ilb22/sureback-fpm_server:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: sureback
            - secretRef:
                name: sureback
      imagePullSecrets:
        - name: registry-secret
