apiVersion: apps/v1
kind: Deployment
metadata:
  name: sureback-queue-worker-default
  labels:
    tier: backend
    layer: queue-worker
    queue: default
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: queue-worker
      queue: default
  template:
    metadata:
      labels:
        tier: backend
        layer: queue-worker
        queue: default
    spec:
      containers:
        - name: queue-worker
          image: asia-southeast2-docker.pkg.dev/sureback-ilb22/sureback/sureback-fpm_server:latest
          # imagePullPolicy: Never
          command:
            - php
          args:
            - artisan
            - queue:work
            - --queue=default
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: sureback
            - secretRef:
                name: sureback
