apiVersion: v1
kind: Service
metadata:
  name: sureback-fpm-dev
  namespace: sureback-dev-mfahmialkautsar
spec:
  selector:
    tier: backend
    layer: fpm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
