name: "Google Artifact Registry"

on:
  workflow_run:
    workflows: ["Laravel"]
    types:
      - completed
    branches:
      - main
      - staging

env:
  APP_DIR: ${{ secrets.APP_DIR }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  deploy-dev:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    env:
      # SSL_CERT: ${{ secrets.SSL_CERT }}
      # SSL_KEY: ${{ secrets.SSL_KEY }}
      FPM_IMAGE: ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_CLUSTER }}/sureback-fpm_server
      WEBSERVER_IMAGE: ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_CLUSTER }}/sureback-web_server
      CRON_IMAGE: ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_CLUSTER }}/sureback-cron
      FRONTEND_IMAGE: ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_CLUSTER }}/sureback-frontend
    steps:
      - uses: actions/checkout@v3
      - name: "Build Docker Image"
        run: |
          docker-compose build
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: "Configure Docker to use the gcloud command-line tool as a credential helper"
        run: |-
          gcloud --quiet auth configure-docker ${{ secrets.GKE_REGION }}-docker.pkg.dev
      - name: "Push Docker Image"
        run: |
          docker push $FPM_IMAGE
          docker push $WEBSERVER_IMAGE
  deploy-staging:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'staging') }}
    env:
      FPM_IMAGE: ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_CLUSTER }}/sureback-fpm_server-staging
      WEBSERVER_IMAGE: ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_CLUSTER }}/sureback-web_server-staging
      CRON_IMAGE: ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_CLUSTER }}/sureback-cron-staging
      FRONTEND_IMAGE: ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_CLUSTER }}/sureback-frontend-staging
    steps:
      - uses: actions/checkout@v3
      - name: "Build Docker Image"
        run: |
          docker-compose build
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: "Configure Docker to use the gcloud command-line tool as a credential helper"
        run: |-
          gcloud --quiet auth configure-docker ${{ secrets.GKE_REGION }}-docker.pkg.dev
      - name: "Push Docker Image"
        run: |
          docker push $FPM_IMAGE
          docker push $WEBSERVER_IMAGE
