name: "Google Kubernetes Engine"

on:
  workflow_run:
    workflows: ["Google Artifact Registry"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Kustomize"
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Get GKE Credentials"
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy
        run: |-
          ./kustomize build kubernetes | kubectl apply -f -
          kubectl rollout restart deployment sureback-fpm
          kubectl rollout restart deployment sureback-queue-worker-default
          kubectl rollout restart deployment sureback-webserver
          kubectl get services -o wide
