name: "Google Kubernetes Engine"

on:
  workflow_run:
    workflows: ["Google Artifact Registry"]
    types:
      - completed
    branches:
      - main
      - staging

jobs:
  get-cloud-service:
    runs-on: ubuntu-latest
    outputs:
      cloud-service: ${{ steps.cloud-service.outputs }}
    steps:
      - run: echo ${{ secrets.CLOUD_SERVICE }}

  deploy-dev:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' && needs.get-cloud-service.outputs.cloud-service == 'GKE' }}
    env:
      DEPLOYMENT_ENV: development
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Kustomize"
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Get GKE Credentials"
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy
        run: |-
          ./kustomize build kubernetes/$DEPLOYMENT_ENV | kubectl apply -f -
          kubectl rollout restart deployment sureback-fpm
          kubectl rollout restart deployment sureback-queue-worker-default
          kubectl rollout restart deployment sureback-webserver
          kubectl get services -o wide
  deploy-staging:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'staging' && needs.get-cloud-service.outputs.cloud-service == 'GKE' }}
    env:
      DEPLOYMENT_ENV: staging
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_STAGING }}
      GKE_ZONE: ${{ secrets.GKE_ZONE_STAGING }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Kustomize"
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Get GKE Credentials"
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy
        run: |-
          ./kustomize build kubernetes/$DEPLOYMENT_ENV | kubectl apply -f -
          kubectl rollout restart deployment sureback-fpm
          kubectl rollout restart deployment sureback-queue-worker-default
          kubectl rollout restart deployment sureback-webserver
          kubectl get services -o wide
